Repository DEPthes/2nd-MVP-Water-Server, pull requests merged in 2023-08, with the labels that each got.

#10 [Fix] #7 BaseResponse Nullable 어노테이션 의존성 수정
  src/main/java/com/example/water/global/BaseResponse.java
Labels: bug

#9 [feat] #2 cicd
  .github/workflows/main.yml
  appspec.yml
  scripts/deploy.sh
Labels: enhancement

#13 [Fix] #12 jasypt 사용 환경변수 암호화
  .github/workflows/main.yml
  build.gradle
  src/main/java/com/example/water/global/config/JasyptConfig.java
  src/main/resources/application.properties
Labels: bug, enhancement

#14 [Feat] #5 #6 카카오 로그인 구현
  build.gradle
  src/main/java/com/example/water/WaterApplication.java
  src/main/java/com/example/water/domain/comment/Comment.java
  src/main/java/com/example/water/domain/crystal/Crystal.java
  src/main/java/com/example/water/domain/emotion/Emotion.java
  src/main/java/com/example/water/domain/user/User.java
  src/main/java/com/example/water/domain/user/UserDto.java
  src/main/java/com/example/water/domain/user/UserRepository.java
  src/main/java/com/example/water/domain/user/UserService.java
  src/main/java/com/example/water/global/auth/KakaoController.java
  src/main/java/com/example/water/global/auth/KakaoService.java
  src/main/resources/application.properties
Labels: enhancement

#22 [Feat] #5 카카오 로그인
  src/main/java/com/example/water/domain/user/UserRepository.java
  src/main/java/com/example/water/domain/user/UserService.java
  src/main/java/com/example/water/global/auth/KakaoController.java
  src/main/java/com/example/water/global/auth/KakaoService.java
Labels: enhancement

#25 [Feat] #5 카카오 로그인 수정사항 반영
  .github/workflows/main.yml
  appspec.yml
  scripts/deploy.sh
  src/main/java/com/example/water/domain/comment/Comment.java
  src/main/java/com/example/water/domain/crystal/Crystal.java
  src/main/java/com/example/water/domain/user/User.java
  src/main/java/com/example/water/global/auth/KakaoController.java
Labels: fix

#27 [Feat] #15 #19 일기 작성
  .gitignore
  build.gradle
  src/main/java/com/example/water/domain/chatGpt/ChatGptController.java
  src/main/java/com/example/water/domain/chatGpt/ChatGptMessage.java
  src/main/java/com/example/water/domain/chatGpt/ChatGptService.java
  src/main/java/com/example/water/domain/chatGpt/config/ChatGptConfig.java
  src/main/java/com/example/water/domain/chatGpt/dto/ChatGptQuestionRequest.java
  src/main/java/com/example/water/domain/chatGpt/dto/ChatGptRequest.java
  src/main/java/com/example/water/domain/chatGpt/dto/ChatGptResponse.java
  src/main/java/com/example/water/domain/comment/Comment.java
  src/main/java/com/example/water/domain/comment/controller/CommentController.java
  src/main/java/com/example/water/domain/comment/dto/request/CommentRequest.java
  src/main/java/com/example/water/domain/comment/dto/request/SaveRequest.java
  src/main/java/com/example/water/domain/comment/repository/CommentRepository.java
  src/main/java/com/example/water/domain/comment/service/CommentService.java
  src/main/java/com/example/water/domain/crystal/Crystal.java
  src/main/java/com/example/water/domain/crystal/repository/CrystalRepository.java
  src/main/java/com/example/water/domain/diary/controller/DiaryController.java
  src/main/java/com/example/water/domain/diary/dto/request/DiaryRequest.java
  src/main/java/com/example/water/domain/diary/dto/response/DiaryResponse.java
  src/main/java/com/example/water/domain/diary/service/DiaryService.java
  src/main/java/com/example/water/domain/emotion/repository/EmotionRepository.java
  src/main/java/com/example/water/global/SuccessCode.java
  src/main/java/com/example/water/global/config/RestTemplateConfig.java
  src/main/resources/application.properties
  src/test/java/com/example/water/domain/diary/service/DiaryServiceTest.java
Labels: enhancement, fix

#28 [Fix] #5 #24 kakao login
  Dockerfile
  src/main/resources/application.properties
Labels: fix

#29 [Fix] userDto에 accessToken 추가
  src/main/java/com/example/water/domain/user/UserDto.java
  src/main/java/com/example/water/global/auth/KakaoController.java
Labels: fix

#32 [Fix] #5 getUserInfo 변수명 수정
  src/main/java/com/example/water/global/auth/KakaoController.java
  src/main/java/com/example/water/global/auth/KakaoService.java
Labels: bug, fix

#33 [Feat] #21 mypage
  src/main/java/com/example/water/domain/comment/dto/response/CommentResponse.java
  src/main/java/com/example/water/domain/comment/entity/Comment.java
  src/main/java/com/example/water/domain/comment/repository/CommentRepository.java
  src/main/java/com/example/water/domain/comment/service/CommentService.java
  src/main/java/com/example/water/domain/crystal/controller/CrystalController.java
  src/main/java/com/example/water/domain/crystal/dto/response/CrystalResponse.java
  src/main/java/com/example/water/domain/crystal/entity/Crystal.java
  src/main/java/com/example/water/domain/crystal/repository/CrystalRepository.java
  src/main/java/com/example/water/domain/crystal/service/CrystalService.java
  src/main/java/com/example/water/domain/diary/controller/DiaryController.java
  src/main/java/com/example/water/domain/diary/service/DiaryService.java
  src/main/java/com/example/water/domain/user/UserService.java
  src/main/java/com/example/water/domain/user/controller/UserController.java
  src/main/java/com/example/water/domain/user/dto/Mypage.java
  src/main/java/com/example/water/domain/user/dto/MypageResponse.java
  src/main/java/com/example/water/domain/user/dto/UserResponse.java
  src/main/java/com/example/water/domain/user/entity/User.java
  src/main/java/com/example/water/domain/user/repository/UserRepository.java
  src/main/java/com/example/water/domain/user/service/UserService.java
  src/main/java/com/example/water/global/auth/controller/KakaoController.java
  src/main/java/com/example/water/global/auth/service/KakaoService.java
Labels: enhancement, fix

#36 [Feat] #34 답변 저장
  src/main/java/com/example/water/domain/comment/controller/CommentController.java
  src/main/java/com/example/water/domain/comment/dto/request/Color.java
  src/main/java/com/example/water/domain/comment/dto/response/CommentResponse.java
  src/main/java/com/example/water/domain/comment/entity/Comment.java
  src/main/java/com/example/water/domain/comment/repository/CommentRepository.java
  src/main/java/com/example/water/domain/comment/service/CommentService.java
  src/main/java/com/example/water/domain/crystal/controller/CrystalController.java
  src/main/java/com/example/water/domain/crystal/entity/Crystal.java
  src/main/java/com/example/water/domain/crystal/repository/CrystalRepository.java
  src/main/java/com/example/water/domain/crystal/service/CrystalService.java
  src/main/java/com/example/water/global/SuccessCode.java
Labels: enhancement

#39 [Feat] #35 update image
  build.gradle
  src/main/java/com/example/water/domain/crystal/controller/CrystalController.java
  src/main/java/com/example/water/domain/crystal/repository/CrystalRepository.java
  src/main/java/com/example/water/domain/crystal/service/CrystalService.java
  src/main/java/com/example/water/domain/user/controller/UserController.java
  src/main/java/com/example/water/domain/user/entity/User.java
  src/main/java/com/example/water/domain/user/service/UserService.java
  src/main/java/com/example/water/global/SuccessCode.java
  src/main/java/com/example/water/global/auth/controller/KakaoController.java
  src/main/java/com/example/water/global/auth/service/KakaoService.java
  src/main/java/com/example/water/global/config/AmazonS3Config.java
  src/main/resources/application.properties
Labels: enhancement, fix

#40 [Fix] fix User null error
  src/main/java/com/example/water/global/auth/service/KakaoService.java
Labels: bug, fix

#41 [Feat] #19 답변 스트림 아닌 문단 전체 한번에 생성
  src/main/java/com/example/water/domain/comment/controller/CommentController.java
  src/main/java/com/example/water/domain/comment/service/CommentService.java
  src/main/java/com/example/water/global/SuccessCode.java
Labels: enhancement

#43 [Feat]#42 결정에 모인 답변 개수 조회
  src/main/java/com/example/water/domain/comment/entity/Comment.java
  src/main/java/com/example/water/domain/comment/repository/CommentRepository.java
  src/main/java/com/example/water/domain/crystal/controller/CrystalController.java
  src/main/java/com/example/water/domain/crystal/service/CrystalService.java
  src/main/java/com/example/water/domain/user/service/UserService.java
  src/main/java/com/example/water/global/SuccessCode.java
Labels: enhancement, fix
